"""Trap database — pattern-matched priors for the search.

A trap is a (FEN-prefix, move) pair that has historically caused humans
to blunder material within a few plies. When the live position matches a
known trap prefix, we bump the corresponding move's troll score so the
search prefers it over freshly-computed alternatives.

The corpus has two sources:

1. `data/known_traps.json` — hand-curated famous traps (Légal, Englund,
   Halloween, Smith-Morra accepted, etc.). Small but high-quality.

2. `data/mined_traps.json` — generated by `data/mine_lichess.py` from
   the Lichess monthly dumps. Large, noisy, sortable by win-rate of
   the lower-rated player.

Both are loaded lazily and merged. Matching is exact on FEN piece
placement + side-to-move + castling rights (we ignore the halfmove
clock and en-passant target for matching flexibility — those rarely
affect whether a trap fires).

Schema (JSON, list of entries):

    [
      {
        "fen_key": "<piece_placement> <stm> <castling>",
        "move_uci": "e2e4",        # the trap move
        "move_san": "e4",
        "name": "Englund Gambit",
        "win_rate": 0.62,          # of the trap-setter, on positions reaching here
        "sample_size": 12345,
        "source": "curated" | "lichess-2024-09",
        "follow_up": ["..."]       # optional: typical winning continuation
      }, ...
    ]
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from functools import lru_cache
from typing import Iterable

import chess


@dataclass
class TrapEntry:
    fen_key: str
    move_uci: str
    move_san: str
    name: str
    win_rate: float
    sample_size: int
    source: str
    follow_up: list[str]


def fen_to_match_key(fen: str) -> str:
    """Strip halfmove-clock and en-passant from a FEN so trap matching
    is robust to minor positional repetitions."""
    parts = fen.split()
    if len(parts) < 3:
        return fen
    # piece-placement, side-to-move, castling, [ep], [halfmove], [fullmove]
    return " ".join(parts[:3])


class TrapDB:
    def __init__(self, *paths: str) -> None:
        self._by_key: dict[str, list[TrapEntry]] = {}
        for p in paths:
            if p and os.path.isfile(p):
                self._load(p)

    def _load(self, path: str) -> None:
        with open(path) as f:
            entries = json.load(f)
        for e in entries:
            entry = TrapEntry(
                fen_key=e["fen_key"],
                move_uci=e["move_uci"],
                move_san=e.get("move_san", e["move_uci"]),
                name=e.get("name", ""),
                win_rate=float(e.get("win_rate", 0.5)),
                sample_size=int(e.get("sample_size", 0)),
                source=e.get("source", ""),
                follow_up=list(e.get("follow_up", [])),
            )
            self._by_key.setdefault(entry.fen_key, []).append(entry)

    def lookup(self, fen: str) -> list[TrapEntry]:
        return list(self._by_key.get(fen_to_match_key(fen), []))

    def __len__(self) -> int:
        return sum(len(v) for v in self._by_key.values())


@lru_cache(maxsize=1)
def default_db() -> TrapDB:
    """Singleton DB loaded from the standard data/ paths."""
    base = os.path.join(os.path.dirname(__file__), "..", "data")
    return TrapDB(
        os.path.join(base, "known_traps.json"),
        os.path.join(base, "mined_traps.json"),
    )


def trap_score_for_move(
    fen: str, move_uci: str, db: TrapDB | None = None
) -> float:
    """How much to bump a candidate move's troll score if it matches a
    known trap. Returns 0 if no match.

    Formula: `300 * win_rate * sqrt(1 - 1/(1 + sample_size/30))`. Up to
    ~+300cp for a heavily-played trap with high win rate; ~+50cp for a
    rarely-seen but successful one. Tunable.
    """
    import math
    db = db or default_db()
    for entry in db.lookup(fen):
        if entry.move_uci == move_uci:
            confidence = math.sqrt(1 - 1.0 / (1 + entry.sample_size / 30.0))
            return 300.0 * entry.win_rate * confidence
    return 0.0
